apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dkpbot.fullname" . }}
  labels:
    {{- include "dkpbot.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "dkpbot.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "dkpbot.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      serviceAccountName: {{ include "dkpbot.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "--config"
            - "/etc/dkpbot/config.yaml"
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            {{- if .Values.cloudnativePG.enabled }}
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.cloudnativePG.clusterName }}-app
                  key: host
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.cloudnativePG.clusterName }}-app
                  key: port
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.cloudnativePG.clusterName }}-app
                  key: user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.cloudnativePG.clusterName }}-app
                  key: password
            - name: DB_DBNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.cloudnativePG.clusterName }}-app
                  key: dbname
            {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.config.server.port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /etc/dkpbot
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: {{ include "dkpbot.fullname" . }}-config
