{{- if .Values.leaderElection.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "dkpbot.fullname" . }}-leader-election
  labels:
    {{- include "dkpbot.labels" . | nindent 4 }}
rules:
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "create", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "dkpbot.fullname" . }}-leader-election
  labels:
    {{- include "dkpbot.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "dkpbot.fullname" . }}-leader-election
subjects:
  - kind: ServiceAccount
    name: {{ include "dkpbot.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
