{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "dkpbot.serviceAccountName" . }}
  labels:
    {{- include "dkpbot.labels" . | nindent 4 }}
{{- end }}
