# Cluster API â€“ Worker MachineDeployment for Hetzner
#
# Creates a pool of worker nodes to run the DKP bot, CloudNative-PG,
# and the observability stack.
# NOTE: The 'replicas' value below is a default. At apply time, bootstrap.yml
# and bootstrap.sh template this value from WORKER_MACHINE_COUNT
# (default: 1) to stay within Hetzner server limits.
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: dkpbot-prod-workers
  namespace: default
spec:
  clusterName: dkpbot-prod
  replicas: 2
  selector:
    matchLabels: {}
  template:
    spec:
      clusterName: dkpbot-prod
      version: v1.31.4
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: KubeadmConfigTemplate
          name: dkpbot-prod-workers
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: HCloudMachineTemplate
        name: dkpbot-prod-workers
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KubeadmConfigTemplate
metadata:
  name: dkpbot-prod-workers
  namespace: default
spec:
  template:
    spec:
      joinConfiguration:
        nodeRegistration:
          kubeletExtraArgs:
            cloud-provider: external
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: HCloudMachineTemplate
metadata:
  name: dkpbot-prod-workers
  namespace: default
spec:
  template:
    spec:
      type: cpx21
      imageName: ubuntu-22.04
